parsers:
- ./parsers/s01-parse/crowdsecurity/modsecurity-nginx-json.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ""
postoverflows:
- ""
log_file: modsecurity-json.log
log_type: modsecurity-nginx-json
ignore_parsers: false
